export const ADD_ADVERTISMENT_REQUEST='ADD_ADVERTISMENT_REQUESR';
export const ADD_ADVERTISMENT_SUCCESS='ADD_ADVERTISMENT_SUCCESS';
export const ADD_ADVERTISMENT_FAILURE='ADD_ADVERTISMENT_FAILURE';

export const DELETE_ADVERTISMENT='DELETE_ADVERTISMENT';
export const UPDATE_ADVERTISMENT='UPDATE_ADVERTISMENT';

export const ALL_ADVERTISMENTS_REQUEST='ALL_ADVERTISMENTS_REQUEST';
export const ALL_ADVERTISMENTS_SUCCESS='ALL_ADVERTISMENTS_SUCCESS';
export const ALL_ADVERTISMENTS_FAILURE='ALL_ADVERTISMENTS_FAILURE';


