//2
export const GET_ALL_CENTERS='GET_ALL_CENTERS';
export const GET_ALL_CENTERS_SUCCESS='GET_ALL_CENTERS_SUCCESS';
export const GET_ALL_CENTERS_FAIL='GET_ALL_CENTERS_FAIL';
export const REGISTER_CENTER='REGISTER_CENTER';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_CENTER_FAIL='REGISTER_CENTER_FAIL';