export const ALL_COUNTRIES_REQUEST='ALL_COUNTRIES_REQUEST';
export const ALL_COUNTRIES_SUCCESS='ALL_COUNTRIES_SUCCESS';
export const ALL_COUNTRIES_FAILURE='ALL_COUNTRIES_FAILURE';

export const SELECT_COUNTRY='SELECT_COUNTRY';

export const ALL_CITIES_REQUEST='ALL_CITIES_REQUEST';
export const ALL_CITIES_SUCCESS='ALL_CITIES_SUCCESS';
export const ALL_CITIES_FAILURE='ALL_CITIES_FAILURE';

export const SELECT_CITIES='SELECT_CITIES';

export const ALL_NATIONALITIES_REQUEST='ALL_NATIONALITIES_REQUEST';
export const ALL_NATIONALITIES_SUCCESS='ALL_NATIONALITIES_SUCCESS';
export const ALL_NATIONALITIES_FAILURE='ALL_NATIONALITIES_FAILURE';

export const SELECT_NATIONALITY='SELECT_NATIONALITY';


export const ALL_CITIES_OF_STATES_REQUEST='ALL_CITIES_OF_STATES_REQUEST';
export const ALL_CITIES_OF_STATES_SUCCESS='ALL_CITIES_OF_STATES_SUCCESS';
export const ALL_CITIES_OF_STATES_FAILURE='ALL_CITIES_OF_STATES_FAILURE';

export const IS_Fetching='IS_Fetching'