//2
export const GET_ALL_TRAINERS='GET_ALL_TRAINERS';
export const GET_ALL_TRAINERS_SUCCESS='GET_ALL_TRAINERS_SUCCESS';
export const GET_ALL_TRAINERS_FAIL='GET_ALL_TRAINERS_FAIL';
export const REGISTER='REGISTER';
export const REGISTER_TRAINER_SUCCESS='REGISTER_TRAINER_SUCCESS';
export const REGISTER_TRAINER_FAIL='REGISTER_TRAINER_FAIL';