export const UPDATEINFO_REQUEST='UPDATEINFO_REQUEST';
export const UPDATEINFO_SUCCESS='UPDATEINFO_SUCCESS';
export const UPDATEINFO_FAILURE='UPDATEINFO_FAILURE';
export const UPDATEPROFESSIONALCARD_REQUEST='UPDATEPROFESSIONALCARD_REQUEST';
export const UPDATEPROFESSIONALCARD_SUCCESS='UPDATEPROFESSIONALCARD_SUCCESS';
export const UPDATEPROFESSIONALCARD_FAILURE='UPDATEPROFESSIONALCARD_FAILURE';
