export const VISITOR_REGISTRATION_REQUEST='VISITOR_REGISTRATION_REQUEST';
export const VISITOR_REGISTRATION_SUCCESS='VISITOR_REGISTRATION_SUCCESS';
export const VISITOR_REGISTRATION_FAILURE='VISITOR_REGISTRATION_FAILURE';
export const VISITOR_LOGIN_REQUEST='VISITOR_LOGIN_REQUEST';
export const VISITOR_LOGIN_SUCCESS='VISITOR_LOGIN_SUCCESS';
export const VISITOR_LOGIN_FAILURE='VISITOR_LOGIN_FAILURE';
export const UPDATE_VISITOR_REQUESTINFO='UPDATE_VISITOR_REQUESTINFO';
export const UPDATE_VISITOR_SUCCESSINFO='UPDATE_VISITOR_REQUESTINFO';
export const UPDATE_VISITOR_FAILUREINFO='UPDATE_VISITOR_REQUESTINFO';
export const UPDATE_NAME='UPDATE_NAME';
export const UPDATE_PASSWORD='UPDATE_PASSWORD';
export const UPDATE_PREFIX='UPDATE_PREFIX';
export const UPDATE_EMAIL='UPDATE_EMAIL';
export const UPDATE_COUNTRYID='UPDATE_COUNTRYID';
export const UPDATE_STATEID='UPDATE_STATEID';
export const UPDATE_NATIONALITYID='UPDATE_NATIONALITYID';
export const UPDATE_PHONE='UPDATE_PHONE'
export const VISITOR_LOGOUT_REQUEST='VISITOR_LOGOUT_REQUEST';
export const VISITOR_LOGOUT_SUCCESS='VISITOR_LOGOUT_SUCCESS';
export const VISITOR_LOGOUT_FAILURE='VISITOR_LOGOUT_FAILURE';


