import LocalizedStrings from "react-native-localization";
export default localization = new LocalizedStrings({
    en: {
        signUpPage: 'signup page',
        forgotPassword: 'forgot password ?',
        rememberMe: ' remember me',
        or: 'or',
        more: 'more',
        joinUs: 'Join us',
        trainer_consultant: 'Trainer/Consultant',
        center: 'Centers',
        visitor: 'Visitor',
        email: 'Email Address',
        password: 'Password',
        trainingCenters_Consultancy: 'Training Centers/Consultancy',
        signIn: ' Sign in',
        management: 'Management',
        Consultancies: 'Consultancies',
        mobileNumber: ' Mobile Number',
        writeMessage: 'Write a message',
        send: 'Send',
        Consultant: 'Consultants',
        save: 'Save',
        memberName: 'Member name',
        city: 'City',
        country: 'Country',
        personalData: ' Personal Information',
        updatePassword: ' Update password',
        SocialMedia: ' Social Media',
        jobCard: 'Job ID',
        mainPage: ' Main Page',
        personalPage: 'Personal page',
        arabicTrainer: 'Arabic Trainer',
        statistics: 'Statistics',
        settings: 'Settings',
        signOut: 'Sign out',
        membership: 'Membership',
        renewMembership: ' Renew Membership',
        Trainer: 'Trainer',
        Mustafa: 'Mustafa',
        Asber: 'Asber',
        Preparing: 'Preparing',
        and: 'and',
        building: 'building',
        training: 'training',
        bags: 'bags',
        Riyadh: 'Riyadh',
        SaudiArabia: 'Saudi Arabia',
        Acertified: 'A certified',
        From: 'From',
        group: 'group',
        Trainers: 'Trainers',
        Activities: 'Activities',
        Centers: 'Centers',
        search: 'Search',
        TrainerName: 'Trainer Name',
        Trainingorconsultingcenter: 'Training or consulting center',
        Neighborhood: 'Neighborhood',
        Nameofspecialization: 'Name of specialization',
        TrainingOpp: ' Training opportunities',
        Tripoli: 'Tripoli',
        Executive: 'Executive',
        Director: 'Director',
        Arab: 'Arab ',
        International: ' International',
        Center: ' Center',
        Lebanon: ' Lebanon ',
        Tripoli: ' Tripoli ',
        Executive: ' Executive ',
        Director: ' Director ',
        SOAcard: 'SOA card',
        Trainingareas: 'Training areas',
        Administrativeandfinancialtraining: 'Administrative and financial training'
        , OccupationalSafetyandHealth: 'Occupational Safety and Health',
        internetConnection: 'please check your internet connection',
        invalidLogin: 'Invalid login',
        oldPassword: 'old password',
        newPassword: 'New password',
        policyUse: 'Rules of Use',
        acceptPolicy: 'I accept policy rules',
        pickCountry: 'Pick country',
        pickCity: 'Pick city',
        pickNationality: 'Pick Nationality',
        policyMessage: 'Please accept the policy',
        requiredFields: 'All fields are required',
        TrainerDetails: 'Trainer Details',
        CenterDetails: 'Center Details',
        ConsultantDetails: 'Consultant Details',
        changeLanguage: ' Change language',
        name: 'Name',
        english: 'English language',
        arabic: 'Arabic language',
        invalidCredentials: 'Invalid credentials',
        updated: 'Updated Successfully',
        required: 'Required',
        phoneValidation: 'The phone must be between 8 and 15',
        mobileValidation: 'The mobile must be a number',
        emailValidation: 'Invalid email address format',
        confirmPassword: 'Confirm Password',
        loginFirst: 'Please login first',
        contactInfo: 'Contact Info',
        basicInfo: 'Basic Info',
        languageSettings: 'Language is set to english',
        passwordValidation: 'Password must be at least 6 characters',
        invalidProfessionalCard: 'You don\'t have professional card',
        invalidData: 'Couldn\'t get data',
        RegisterCenter: 'Registration (Center / Training Institute or Consulting)',
        AbouttheCenter: 'About the Center',
        Name: 'Name: Center / Training Institute - Consulting Office',
        placeholder50: '50 letters',
        manager: 'manager',
        YearFounded: 'Year Founded',
        country: 'country',
        ProfessionalInformation: 'Professional Information',
        Areas: 'Areas:Training / Consulting - Home',
        ProfessionalCard: 'Professional card for: Coach / Counselor',
        DesignCard: 'Design your service card',
        Meansofcommunication: 'Means of communication',
        email: 'Email',
        phone: 'Phone',
        website: 'website',
        password: 'password',
        confirmPassword: 'Confirm Password',
        show: 'Show',
        Subscription: 'Subscription',
        moneyAmount: 'Only B: SR 0.75 per day',
        months6: '6 months',
        months12: '12 months',
        Saudiriyals: 'Add 0.75 Saudi riyals to always appear at the forefront of research',
        Clicktopay: 'Click to pay',
        Register: 'Register',
        RegisterSuccessTrainer: 'Honors Gentlemen Institute of Training Center - Consulting God bless you  Arab International Coach Group - Lebanon Thank you for joining the "Arab Trainer" We hope you will check your e-mail to activate your account In the application and use of its services welcome',
        RegisterSuccess: 'Honors Gentlemen Institute of Training Center - Consulting God bless you Arab International Coach Group - Lebanon Thank you for joining the "Arab Trainer" We hope you will check your e-mail to activate your account In the application and use of its services welcome'
        , RegisterSuccessVisitor: 'Welcome to God Arab International Coach Group - Lebanon Thank you for joining the "Arab Trainer"  We hope you will check your e-mail to activate your account In the application and use of its services welcome',
        upladImage: 'Press to upload an image',
        pay: 'Press to pay',
        RegisterCenter: 'Registration (Center / Training Institute or Consulting)',
        AbouttheCenter: 'About the Center',
        Name: 'Name: Center / Training Institute - Consulting Office',
        placeholder50: '50 letters',
        manager: 'manager',
        YearFounded: 'Year Founded',
        country: 'country',
        city: 'city',
        ProfessionalInformation: 'Professional Information',
        Areas: 'Areas:Training / Consulting - Home',
        ProfessionalCard: 'Professional card for: Coach / Counselor',
        DesignCard: 'Design your service card',
        Meansofcommunication: 'Means of communication',
        UploadPhoto: 'Click to upload your photo',
        show: 'Show',
        Subscription: 'Subscription',
        moneyAmount: 'Only B: SR 0.75 per day',
        months6: '6 months',
        months12: '12 months',
        Saudiriyals: 'Add 0.75 Saudi riyals to always appear at the forefront of research',
        sex:'Sex',
        nationality:'Nationality',
        character:'Character',
        primaryAccreditation:'Primary Accreditation',
        characterPlaceholder:'Doctor / Advisor / Professor',
        trainingTours:'Top Three: Training Courses / Advisory Titles',
        registerVisitorWelcomeText:'Welcome Guest We hope you will benefit and find what you are looking for in applying the Arab Trainer',
        registerVisitor:'Please register to be able to search and view the contents of the application',
        visitorRegistration:'Visitor registration',
        registerTrainer:'Register trainer/consultant',
        numVisits:'Number of visits',
        appearedSearch:'You have appeared in search',
        searchResults:'Search Results',
        facebookUrl:"Please enter your facebook url",
        linkedinUrl:"Please enter your linkedin url",
        twitterUrl:"Please enter your twitter url",
        snapchatUrl:"Please enter your snapchat url",
        youtubeUrl:"Please enter your youtube url",
        telegramUrl:"Please enter your telegram url",
        instagramUrl:"Please enter your instagram url",
        whatsappUrl:"Please enter your Whatsapp number",

        send:"Send",
        cancel:"Cancel",
        yearfoundedValidation:"Year founded must be between 1500 and 2019",
        yearfoundedNumValidation:"Year founded must be a number",
        male:'Male',
        // smallMale:'male',
       female:'Female',
        // smallFemale:'female',
        instatue:'instatue',
        Cen:'center',
        department:'department',
        welcome: 'ًًWelcom to Almodarb Alarby',
        firstapp: 'The first specialized application of the community for training and consulting',
        inOnePlace: 'In One Place',
        trainingCenterCardItem: 'The safe and professional reference of the training community',

    },
    ar: {
        signUpPage: 'صفحة تسجيل',
        trainingCenterCardItem: 'الوجهة الامنة و المرجعية المهنية و القانونية لمجتمع التدريب',
        welcome: ' اهلا و سهلا بكم في تطبيق المدرب العربي ',
        firstapp: 'أول تطبيق متخصص بالمجتمع للتدريب والاستشارات',
        inOnePlace: '  في مكان واحد',
        forgotPassword: ' هل نسيت كلمة المرور ؟',
        rememberMe: 'تذكرنى',
        or: 'أو',
        joinUs: 'انضم إلينا',
        trainer_consultant: 'مدرب/مستشار',
        trainingCenters_Consultancy: ' التدريب / الاستشارات',
        center: 'مراكز',
        visitor: 'زائر',
        email: 'البريد الإلكتروني',
        password: 'كلمه السر',
        signIn: 'تسجيل الدخول',
        management: 'الإدارة',
        Consultancies: 'الاستشارات',
        mobileNumber: 'رقم الجوال',
        writeMessage: 'اكتب الرسالة',
        send: 'إرسال',
        Consultant: 'الاستشاريين',
        save: 'حفظ',
        memberName: 'اسم عضو',
        country: 'دولة',
        city: 'مدينة',
        personalData: 'بيانات شخصية',
        updatePassword: 'تعديل كلمة المرور ',
        SocialMedia: ' وسائل التواصل الاجتماعي',
        socialMediaProfile: ' حسابات التواصل الاجتماعي',
        jobCard: 'بطاقة مهنية',
        more: 'المزيد',
        mainPage: 'الصفحة الرئيسية',
        personalPage: 'الصفحة الشخصية',
        arabicTrainer: 'المدرب العربي',
        statistics: 'الإحصائيات',
        settings: 'الإعدادات',
        signOut: 'تسجيل الخروج',
        membership: 'الاشتراك',
        renewMembership: ' تسجيل الاشتراك',
        Trainer: 'المدرب',
        Mustafa: 'مصطفى',
        Asber: 'اسبر',
        Preparing: 'اعداد',
        and: 'و',
        building: 'بناء',
        training: 'التدريبية',
        bags: 'الحقائب',
        Riyadh: 'الرياض',
        SaudiArabia: 'السعودية',
        Acertified: 'معتمد',
        From: 'من',
        group: 'مجموعة',
        Activities: 'نشاطات',
        Centers: 'مراكز',
        Trainers: 'المدربين',
        search: 'البحث',
        TrainerName: 'اسم المدرب',
        Trainingorconsultingcenter: 'مركز تدريب او استشارات',
        Neighborhood: 'الحى',
        Nameofspecialization: 'اسم التخصص',
        TrainingOpp: 'فرص تدريبية',
        Center: 'مركز',
        Arab: ' العربى',
        International: ' الدولى',
        Lebanon: ' لبنان',
        Tripoli: '  طرابلس',
        Director: ' المدير',
        Executive: ' التنفيذى',
        SOAcard: 'البطاقة الخدمية',
        Trainingareas: "مجالات التدريب ",
        Administrativeandfinancialtraining: 'التدريب الأدارى و المالى',
        OccupationalSafetyandHealth: 'السلامة والصحة المهنية',
        internetConnection: 'الرجاء التحقق من اتصال الانترنت الخاص بك',
        invalidLogin: 'تسجيل الدخول غير صالح',
        oldPassword: 'كلمة السر القديمة',
        newPassword: 'كلمة السر الجديدة',
        policyUse: 'قواعد الاستخدام',
        acceptPolicy: 'قبول شروط الاستخدام',
        pickCountry: 'اختر دولة ',
        pickCity: 'اختر المدينة',
        pickNationality:'اختر الجنسية',
        policyMessage: 'يرجى قبول شروط الاستخدام ',
        requiredFields: 'جميع الحقول مطلوبة',
        NewChanges: 'شريط يظهر فيه أى اضافة تمت فى التطبيق',
        TrainerDetails: 'تفاصيل المدرب',
        CenterDetails: 'تفاصيل المركز',
        ConsultantDetails: 'تفاصيل المستشار',
        changeLanguage: 'تغيير اللغة',
        name: 'اسم',
        arabic: 'اللغة العربية',
        english: 'اللغة الانجليزية',
        invalidCredentials: 'بيانات الاعتماد غير صالحة',
        updated: 'تم التحديث بنجاح',
        required: 'مطلوب',
        registerTrainer:'(التسجيل (مدرب / ة - مستشار',
        exactPassword: 'تأكيد كلمة المرور يجب أن تكون كلمة مرور متساوية',
        phoneValidation: 'يجب أن يكون الهاتف بين ٨ و ١٥',
        mobileValidation: 'يجب أن يكون الجوال رقمًا',
        emailValidation: 'تنسيق البريد الإلكتروني غير صالح',
        confirmPassword: 'تأكيد كلمة السر',
        loginFirst: 'الرجاء تسجيل الدخول أولا',
        contactInfo: 'معلومات الاتصال',
        basicInfo: 'معلومات أساسية',
        languageSettings: 'تم تعيين اللغة العربية',
        passwordValidation: 'يجب أن تتكون كلمة المرور من ٦ أحرف على الأقل',
        invalidProfessionalCard: 'ليس لديك بطاقة مهنية ',
        invalidData: 'لا يمكن الحصول على البيانات',
        RegisterSuccessTrainer: 'المكرم الزميل المدرب / المدربة - المستشار / المستشارة حفظك الله  ترحب بكم  أدارة مجموعة المدرب العربى الدولية - لبنان نشكركم على انضمامكم لتطبيق "المدرب العربى" نأمل منكم مراجعة بريدكم الاكترونى لتفعيل حسابكم فى التطبيق و الاستفادة من خدماته أهلا وسهلا بكم '
        , RegisterSuccess: 'المكرمين السادة معهد ظ مركز التدريب - الاستشارات  حفظك الله ترحب بكم أدارة مجموعة المدرب العربى الدولية - لبنان نشكركم على انضمامكم لتطبيق "المدرب العربى" نأمل منكم مراجعة بريدكم الاكترونى لتفعيل حسابكم فى التطبيق و الاستفادة من خدماته أهلا وسهلا بكم',
        RegisterSuccessVisitor: '  عزيزى الزائر حفظك الله ترحب بكم أدارة مجموعة المدرب العربى الدولية - لبنان نشكركم على انضمامكم لتطبيق "المدرب العربى" نأمل منكم مراجعة بريدكم الاكترونى لتفعيل حسابكم فى التطبيق و الاستفادة من خدماته أهلا وسهلا بكم ',
        upladImage: 'اضغط لتحميل صورتك',
        Register: 'تسجيل',
        pay: 'اضغط للدفع',
        RegisterCenter: ' التسجيل (مركز / معهد تدريب أو استشارات) ',
        AbouttheCenter: 'عن المركز',
        Name: 'اسم : مركز / معهد التدريب - مكتب الاستشارات',
        placeholder50: '50 حرف',
        manager: 'المدير',
        YearFounded: 'سنة التأسيس',
        ProfessionalInformation: 'معلومات مهنية ',
        Areas: 'مجالات : التدريب / الاستشارات - الرئيسية',
        ProfessionalCard: 'البطاقة المهنية ل : مدرب / المستشار',
        DesignCard: 'صمم بطاقتك الخدمية',
        Meansofcommunication: 'وسائل التواصل',
        show: 'معاينة',
        Subscription: 'الاشتراك',
        moneyAmount: 'فقط ب : 0.75 ريال سعودى يوميا',
        months6: '6 شهور',
        months12: '12 شهر',
        Saudiriyals: 'أضف 0.75 ريال سعودى للظهور دوما فى مقدمة البحث',
        sex:'الجنس',
        nationality:'الجنسية',
        character:'الصفة',
        primaryAccreditation:'جهة الاعتماد الاساسية',
        characterPlaceholder:'دكتور / مستشار / أستاذ',
        trainingTours:'أهم ثلاث : دورات تدريبية / عناوين استشارية',
        registerVisitorWelcomeText:' مرحبا بك أيها الزائر الكريم نأمل أن تستفيد و تجد ما تبحث عنه فى تطبيق المدرب العربى ',
        registerVisitor:'يرجى التسجيل لتستطيع البحث والاطلاع على محتويات التطبيق',
        visitorRegistration:'تسجيل زائر',
        numVisits:'عدد الزيارات',
        appearedSearch:'لقد ظهرت في البحث',
        searchResults:'نتائج البحث',
        facebookUrl:"من فضلك ادخل رابط الفيسبوك الخاص بك",
        linkedinUrl:"يرجى إدخال رابط لينكدن الخاص بك",
        youtubeUrl:"يرجى إدخال رابط اليوتيوب الخاص بك",
        instagramUrl:"الرجاء إدخال رابط الانستجرام الخاص بك",
        snapchatUrl:"الرجاء إدخال رابط سناب شات الخاص بك",
        telegramUrl:"الرجاء إدخال رابط telegram الخاص بك",
        twitterUrl:"الرجاء إدخال رابط twitter الخاص بك",
        whatsappUrl:"الرجاء إدخال رقم Whatsapp الخاص بك",
        send:"إرسال",
        cancel:"إلغاء",
        yearfoundedValidation:'يجب أن يكون عام التأسيس بين 1500 و 2019',
        yearfoundedNumValidation:'يجب أن يكون عام التأسيس رقمًا',
        male:'ذكر',
        // smallMale:'male',
       female:'إنثي',
    instatue:'معهد',
    Cen:'مركز',
    department:'المؤسسة'

    }
})
